# Optimization Defaults
DEFAULT_OPTIMIZATION_SAMPLES = 5_000

# Search Space Bounds
MAX_MACHINES_PER_TYPE = 50
MAX_BATTERIES = 25
MAX_BATTERY_HEIGHT = 50

# NSGA-II Hyperparameters
POPULATION_SIZE = 40
CROSSOVER_PROBABILITY = 0.9
CROSSOVER_ETA = 15
MUTATION_PROBABILITY = 0.1
MUTATION_ETA = 20

# Selection Logic
DEFAULT_TARGET_UNRELIABILITY = 0.05

# Termination
DEFAULT_MAX_TIME_SECONDS = 40
