HOURS_PER_DAY = 24

# Simulation Defaults
DEFAULT_DAYS = 132
DEFAULT_WORKING_HOURS = 16

# Machine Count Defaults
DEFAULT_LUMBER_MILLS = 1
DEFAULT_GEAR_WORKSHOPS = 1
DEFAULT_STEEL_FACTORIES = 1
DEFAULT_WOOD_WORKSHOPS = 1
DEFAULT_PAPER_MILLS = 1
DEFAULT_PRINTING_PRESSES = 2
DEFAULT_OBSERVATORIES = 4
DEFAULT_BOT_PART_FACTORIES = 3
DEFAULT_BOT_ASSEMBLERS = 1
DEFAULT_EXPLOSIVES_FACTORIES = 0
DEFAULT_GRILLMISTS = 1
DEFAULT_WATER_WHEELS = 5
DEFAULT_LARGE_WINDMILLS = 15
DEFAULT_WINDMILLS = 0
DEFAULT_BATTERIES = 3
DEFAULT_BATTERY_HEIGHT = 15

# Season Defaults
DEFAULT_WET_SEASON_DAYS = 3
DEFAULT_DRY_SEASON_DAYS = 30
DEFAULT_BADTIDE_SEASON_DAYS = 30

# Wind Simulation
WIND_DURATION_MIN_HOURS = 5
WIND_DURATION_MAX_HOURS = 13  # Exclusive for randint (5-12 hours)
LARGE_WINDMILL_THRESHOLD = 0.20
SMALL_WINDMILL_THRESHOLD = 0.30

# Optimization Defaults
DEFAULT_OPTIMIZATION_ITERATIONS = 150
DEFAULT_SIMULATIONS_PER_CONFIG = 500
