name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint with Ruff
        run: poetry run poe lint

      - name: Typecheck with Mypy
        run: poetry run poe typecheck

      - name: Run tests with Pytest
        run: poetry run poe test
